### ISSUE TITLE
Feature Request: Channel Tag

### ISSUE THREAD

**Issue by mpearon** [MediaBrowser/Pushbullet#1]
Adding a channel tag to the Pushbullet plugin would bring this in line with other mediaserver-related products.

These are all basically the same product, but they might provide a little guidance:
https://github.com/Sonarr/Sonarr/tree/phantom-develop/src/NzbDrone.Core/Notifications/PushBullet
https://github.com/Radarr/Radarr/tree/develop/src/NzbDrone.Core/Notifications/PushBullet
https://github.com/lidarr/Lidarr/tree/develop/src/NzbDrone.Core/Notifications/PushBullet

According to this, it looks like `channel_tag` can just be passed in the JSON body:
https://github.com/tidusjar/Ombi/blob/feature/v4/src/Ombi.Api.Pushbullet/PushbulletApi.cs

A field would need to be added to the UI that would be passed in to the JSON body.

**Comment by mpearon** [comment]
I've never done it, but would a pull request be appropriate in this situation?

**Comment by LukePulverenti** [comment]
Hi, yes pull requests are welcome !

**Comment by mpearon** [comment]
@LukePulverenti - Okay, I did what I **think** was correct. :)
I'm learning out loud here, so don't hesitate to tell me I did something stupid.

https://github.com/MediaBrowser/Pushbullet/pull/2

**Comment by mpearon** [comment]
Closed via #2 / https://github.com/MediaBrowser/Pushbullet/commit/9e97c9f2f65f4b73e2e5a27b6d7960d09405a6e3
